---
name: service-metrics-injector

stemcells:
- alias: trusty
  os: ubuntu-xenial
  version: latest

releases:
- name: service-metrics
  version: latest
- name: loggregator
  version: latest
- name: loggregator-agent
  version: latest
- name: bpm
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: service-metrics
  instances: 1
  stemcell: trusty
  vm_type: minimal
  networks:
  - name: default
  azs:
  - z1
  jobs:
  - name: service-metrics
    release: service-metrics
    properties:
      service_metrics:
        origin: service-metrics-injector
        execution_interval_seconds: 5
        metrics_command: /bin/echo
        metrics_command_args:
        - -n
        - '[{"key":"service-dummy","value":99,"unit":"metric"}]'
        monit_dependencies: []
        tls:
          cert: ((service-metrics.certificate))
          key: ((service-metrics.private_key))
          ca: ((service-metrics.ca))

  - name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler: {from: doppler, deployment: loggregator}
    properties:
      disable_udp: true
      loggregator:
        tls:
          agent:
            cert: ((loggregator_agent.certificate))
            key: ((loggregator_agent.private_key))
          ca_cert: ((loggregator_agent.ca))


variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: service-metrics
  type: certificate
  options:
    ca: loggregator_ca
    common_name: service-metrics
    extended_key_usage:
    - client_auth
- name: loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: agent
    alternative_names:
    - metron
    - agent
    - localhost
    - 127.0.0.1
    - ip6-localhost
    - ::1
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000


