disable_ssl_cert_verification: false # When talking to cf, don't verify the certificates

broker_name: # Name of the broker, as registered with CF
broker_uri:
broker_route_name: # ID of the route, as registered with the Go Router (cf). Used in the route_registrar

service_catalog_id: # Unique ID for the service, as displayed in the /v2/services unique_id
service_catalog_service_name: # Label for the service, as displayed in the cf marketplace

bosh:
  url:
  root_ca_cert:
  authentication:
    username:
    password:

cf:
  api_url:
  root_ca_cert:
  uaa:
    url:
    ca_cert: # Required if secure bindings are enabled
  user_credentials:
    username:
    password:
