---
name: service-metrics

director_uuid: e92258ed-c38a-4ea1-b7d4-fbef77d8e5d0

releases:
- name: service-metrics
  version: latest

properties:
  service_metrics:
    execution_interval_seconds: 5
    metrics_command: /bin/echo
    metrics_command_args:
    - -n
    - '[{"key":"service-dummy","value":99,"unit":"metric"}]'
  etcd:
    machines:
    - 10.0.16.104
  metron_agent:
    deployment: bosh-aws
    zone: z1
  loggregator_endpoint:
    shared_secret: raicVesOldIdWyntedquadwyWokFafBi
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
  nats:
    machines: 
    - 10.0.16.103
    port: 4222
    user: nats
    password: jodumNehozBusItOijyoczimyivoffan

jobs:
- name: service-metrics
  instances: 1
  resource_pool: service-metrics
  networks:
  - name: service-metrics
  templates:
  - {release: service-metrics, name: service-metrics}

networks:
- name: service-metrics
  subnets:
  - range: 10.0.18.0/24
    gateway: 10.0.18.1
    reserved:
    - 10.0.18.2 - 10.0.18.4
    - 10.0.18.254
    cloud_properties:
      subnet: subnet-71e16528

resource_pools:
- name: service-metrics
  network: service-metrics
  cloud_properties:
    instance_type: m3.medium
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3019

compilation:
  workers: 1
  network: service-metrics
  cloud_properties:
    instance_type: m3.medium

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

