---
groups:
- name: main
  jobs:
  - bump-major
  - deploy-release
  - release-test
  - build-final
  - promote
  - release

- name: merge
  jobs:
  - merge-master-into-develop

resources:
- name: develop
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release
    ignore_paths:
    - releases

- name: develop-sink
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: master
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: service-metrics
    ignore_ssl: true

- name: s3-bucket
  type: s3
  source:
    bucket: cf-services-internal-builds
    regexp: service-metrics-(.*).tgz
    access_key_id: {{release-bucket-access-key}}
    secret_access_key: {{release-bucket-secret-key}}

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    bucket: ci-versions
    key: service-metrics-dev
    access_key_id: {{release-bucket-access-key}}
    secret_access_key: {{release-bucket-secret-key}}
    region_name: eu-west-1

jobs:
- name: bump-major
  serial: true
  plan:
  - aggregate:
    - get: version
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: deploy-release
  serial: true
  plan:
  - aggregate:
    - get: develop
      trigger: true
    - get: aws-stemcell
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}
  - task: create-release
    file: develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: true
        FINAL: false
  - put: bosh
    params:
      manifest: develop/manifests/service-metrics-aws.yml
      stemcells:
      - aws-stemcell/**/*.tgz
      releases:
        - create-release/develop/dev_releases/**/*.tgz

- name: release-test
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [deploy-release]
      trigger: true
    - get: develop
      trigger: true
      passed: [deploy-release]
  - task: release-test
    file: develop/ci/release-test.yml
    privileged: true
    config:
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        DOPPLER_ADDR: {{doppler-addr}}

- name: build-final
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [release-test]
      trigger: true
    - get: develop
      trigger: true
      passed: [release-test]
      params: {fetch: [master]} 
  - task: create-release
    file: develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: false
        FINAL: true
        S3_ACCESS_KEY: {{release-bucket-access-key}}
        S3_SECRET_KEY: {{release-bucket-secret-key}}
  - aggregate:
    - put: s3-bucket
      params: 
        from: create-release/develop/releases/service-metrics/service-metrics-(.*).tgz
        to: service-metrics/
    - put: master
      params:
        repository: create-release/develop

- name: promote
  serial: true
  plan:
  - aggregate:
    - get: master
      passed: [build-final]
    - get: version
      params: {bump: final}
      passed: [build-final]
  - put: version
    params: {file: version/number}

- name: release
  serial: true
  plan:
  - aggregate:
    - get: version
      trigger: true
      passed: [promote]
    - get: master
      passed: [promote]
  - task: create-release
    file: master/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: false
        FINAL: true
        S3_ACCESS_KEY: {{release-bucket-access-key}}
        S3_SECRET_KEY: {{release-bucket-secret-key}}
  - aggregate:
    - put: s3-bucket
      params: 
        from: create-release/master/releases/service-metrics/service-metrics-(.*).tgz
        to: service-metrics/
    - put: master
      params:
        repository: create-release/master
        tag: version/number
        tag_prefix: v

- name: merge-master-into-develop
  serial: true
  plan:
    - get: master
      trigger: true
      params:
        fetch: [develop]
    - task: merge-to-develop
      file: master/ci/merge-to-develop.yml
    - put: develop-sink
      params:
        repository: merge-to-develop/master
