---
resources:
- name: service-metrics-release-develop
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: service-metrics-release-master
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: service-metrics
    ignore_ssl: true

- name: final-release
  type: s3
  source:
    bucket: cf-services-internal-builds
    regexp: service-metrics-(.*).tgz
    access_key_id: {{release-bucket-access-key}}
    secret_access_key: {{release-bucket-secret-key}}

jobs:
- name: deploy-release
  plan:
  - get: service-metrics-release-develop
    trigger: true
  - get: aws-stemcell
  - task: create-release
    file: service-metrics-release-develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: true
        FINAL: false
  - put: bosh
    params:
      manifest: service-metrics-release-develop/manifests/service-metrics-aws.yml
      stemcells:
      - aws-stemcell/**/*.tgz
      releases:
        - create-release/service-metrics-release-develop/dev_releases/**/*.tgz

- name: release-test
  plan:
  - get: service-metrics-release-develop
    trigger: true
    passed: [deploy-release]
  - task: release-test
    file: service-metrics-release-develop/ci/release-test.yml
    privileged: true
    config:
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        DOPPLER_ADDR: {{doppler-addr}}

- name: ship-it
  plan:
  - get: service-metrics-release-develop
    trigger: true
    passed: [release-test]
  - task: create-release
    file: service-metrics-release-develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: false
        FINAL: true
        S3_ACCESS_KEY: {{release-bucket-access-key}}
        S3_PRIVATE_KEY: {{release-bucket-secret-key}}
  - put: final-release
    params: 
      from: create-release/service-metrics-release-develop/releases/service-metrics/service-metrics-(.*).tgz
      to: service-metrics

- name: promote-to-master
  plan:
  - get: service-metrics-release-develop
    trigger: true
    passed: [release-test]
  - put: service-metrics-release-master
    params:
      repository: service-metrics-release-develop
