---
resources:
- name: service-metrics-release-develop
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: service-metrics-release-master
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: service-metrics-release

jobs:
- name: deploy-release
  plan:
  - get: service-metrics-release-develop
    trigger: true
  - get: aws-stemcell
  - task: create-release
    file: service-metrics-release-develop/ci/create-release.yml
    privileged: true
  - put: bosh
    params:
      manifest: service-metrics-release-develop/manifests/service-metrics-aws.yml
      stemcells: aws-stemcell/**/*.tgz
      releases: service-metrics-release-develop/dev_releases/**/*.tgz

- name: release-test
  plan:
  - get: service-metrics-release-develop
    trigger: true
    passed: [deploy-release]
  - task: release-test
    file: service-metrics-release-develop/ci/release-test.yml
    privileged: true
    config:
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        DOPPLER_ADDR: {{doppler-addr}}

- name: promote-to-master
  plan:
  - get: service-metrics-release-develop
    trigger: true
    passed: [release-test]
  - put: service-metrics-release-master
    params:
      repository: service-metrics-release-develop
