---
resources:
- name: service-metrics-release-develop
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release
    ignore_paths:
    - releases/

- name: service-metrics-release-master
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-metrics-release

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: service-metrics
    ignore_ssl: true

- name: final-release
  type: s3
  source:
    bucket: cf-services-internal-builds
    regexp: service-metrics-(.*).tgz
    access_key_id: {{release-bucket-access-key}}
    secret_access_key: {{release-bucket-secret-key}}

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    bucket: ci-versions
    key: service-metrics-dev
    access_key_id: {{release-bucket-access-key}}
    secret_access_key: {{release-bucket-secret-key}}
    region_name: eu-west-1

jobs:
- name: deploy-release
  serial: true
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}
  - get: service-metrics-release-develop
    trigger: true
  - get: aws-stemcell
  - task: create-release
    file: service-metrics-release-develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: true
        FINAL: false
  - put: bosh
    params:
      manifest: service-metrics-release-develop/manifests/service-metrics-aws.yml
      stemcells:
      - aws-stemcell/**/*.tgz
      releases:
        - create-release/service-metrics-release-develop/dev_releases/**/*.tgz

- name: release-test
  plan:
  - get: version
    passed: [deploy-release]
  - get: service-metrics-release-develop
    trigger: true
    passed: [deploy-release]
  - task: release-test
    file: service-metrics-release-develop/ci/release-test.yml
    privileged: true
    config:
      params:
        CF_API: {{cf-api}}
        CF_USERNAME: {{cf-username}}
        CF_PASSWORD: {{cf-password}}
        DOPPLER_ADDR: {{doppler-addr}}

- name: build-final
  plan:
  - get: version
    passed: [release-test]
  - get: service-metrics-release-develop
    trigger: true
    passed: [release-test]
    params: {fetch: [master]} 
  - task: create-release
    file: service-metrics-release-develop/ci/create-release.yml
    config:
      params:
        NAME: service-metrics
        FORCE: false
        FINAL: true
        S3_ACCESS_KEY: {{release-bucket-access-key}}
        S3_SECRET_KEY: {{release-bucket-secret-key}}
  - put: final-release
    params: 
      from: create-release/service-metrics-release-develop/releases/service-metrics/service-metrics-(.*).tgz
      to: service-metrics/
  - put: service-metrics-release-master
    params:
      repository: create-release/service-metrics-release-develop

- name: merge-master-into-develop
  plan:
    - aggregate:
      - get: service-metrics-release-master
        trigger: true
        params:
          fetch: [develop]
    - task: merge-to-develop
      file: service-metrics-release-master/ci/merge-to-develop.yml
    - put: service-metrics-release-develop
      params:
        repository: merge-to-develop/service-metrics-release-master
